// One copy shared by the app and the daemon: a mirrored crypto protocol that drifts could quietly agree on something weaker.
// No Buffer or other Node global: packages/web typechecks with no Node types.
export {
  FRAME,
  LengthReader,
  MAX_FRAME_PAYLOAD,
  MAX_HEADER_JSON_BYTES,
  MAX_SOCKET_MESSAGE_BYTES,
  MessageAssembler,
  decodeFrame,
  decodeJson,
  encodeFrame,
  encodeJsonFrame,
  encodeMessageFrames,
  frameLength,
  tryEncodeJsonFrame,
  type CloseFrame,
  type FrameType,
  type HelloFrame,
  type OpenFrame,
  type RequestFrame,
  type ResponseFrame,
} from "./frames.js";
export {
  CipherState,
  generateStaticKey,
  localStaticKey,
  NoiseHandshake,
  publicFromSecret,
  randomSecretKey,
  type Ephemeral,
  type NoiseOptions,
  type NoiseTransport,
  type StaticKey,
} from "./noise.js";
